### ISSUE TITLE
🐊 Who's using CrocodileJS?

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#129]
🐊  Add yourself or someone you know!

**Comment by xthilakx** [comment]
I was looking for options after I decided to move away from Express. Just found Glazed this weekend, and currently building something with it. Thanks for putting this together! 

FYI, a link on your website leads to 404 - `https://github.com/koajs/koahttps://github.com/glazedio/glazed/blob/master/docs/koa-vs-express.md`

**Comment by niftylettuce** [comment]
Thanks!  I'll fix this

**Comment by niftylettuce** [comment]
@xthilakx How did you find Glazed btw?

**Comment by xthilakx** [comment]
@niftylettuce I was searching for an opinionated stack to build an API. Someone on Reddit pointed me to your repo.

**Comment by andreasvirkus** [comment]
So this issue is supposed to be a "See who else uses crocodile" resource but is... completely empty? Where would one get some actual examples of crocodile usage or any reference to people using it?

**Comment by niftylettuce** [comment]
@andreasvirkus sorry I need to make it more apparent - we are gearing up for a stable release and a complete rebranding from "Crocodile" to simply "Lad".  References + code snippets + screencasts + live coding will come soon.  If you want to get access to this as soon as its released (should be within the next week I hope) please join us in Slack at <http://slack.crocodilejs.com/.
