### ISSUE TITLE
The crocodilejs.com website is not working

### ISSUE THREAD

**Issue by rsp** [ladjs/lad#219]
The website linked on https://github.com/crocodilejs and in this project's page https://github.com/crocodilejs/crocodile-node-mvc-framework is:
- https://crocodilejs.com/

Few days ago it used to warn about bad certificate and if accessed despite the warning gave 404 error. The http version:
- http://crocodilejs.com/

also gave 404. Currently trying to connect to both http and https versions result in Connection refused error.

**Comment by niftylettuce** [comment]
I haven't released v1.0.0 yet, once that is done (hopefully this week, it will be up!).

Join Slack if you haven't already!  http://slack.crocodilejs.com/

**Comment by reneras** [comment]
What's holding you back to release ? How can we help ?
Thanks

**Comment by bsodmike** [comment]
Same here @niftylettuce I'm happy to help.
