### ISSUE TITLE
indeterministic job runners?

### ISSUE THREAD

**Issue by weisjohn** [ladjs/lad#225]
I have a job called `product` which runs just like `locales`

in jobs/indexjs:

```
  getJobs() {
    return [
      [ 'email', {}, this.email ],
      [ 'product', {}, this.product ]
    ];
  }
```

in agenda.js:

```
agenda.now('product');
```

Sometimes I see more than one start:

```
info: mongoose connection open to mongodb://localhost:27017/app_development
info: agenda ready
info: agenda opened connection using existing mongoose connection
info: job "product" started
info: job "product" started
info: job "product" started
info: job "product" started
info: job "product" started
```

And other times, I see exactly one start:

```
info: mongoose connection open to mongodb://localhost:27017/hvaczap_development
info: agenda ready
info: agenda opened connection using existing mongoose connection
info: job "product" started
calling done
info: job "product" succeeded
info: job "product" completed
```

Is this a problem with config, agenda?

basically, if I SIGINT agenda, it has a graceful period, but my job won’t complete in that amount of time

**Comment by weisjohn** [comment]
from chat: 


niftylettuce [10:55 AM]  
oh

[10:55]  
yeah thats probably the issue

[10:56]  
maybe listen for an event and have a `.on` event listener

[10:56]  
which would stop it / pause

[11:00]  
that would be a cool invention

[11:00]  
event emitter when graceful restart

[11:00]  
so u can stop a job

**Comment by timelf123** [comment]
Try this:

```
function graceful() {
  agenda.stop(function() {
    process.exit(0);
  });
}

process.on('SIGTERM', graceful);
process.on('SIGINT' , graceful);
```
