### ISSUE TITLE
Cant create new project

### ISSUE THREAD

**Issue by chaddy012** [ladjs/lad#236]
* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by niftylettuce** [comment]
@chaddy012 @tomoat I'll have this released publicly soon -- in meanwhile you can just clone the dev branch probably to get going (don't use the CLI yet)

**Comment by niftylettuce** [comment]
thanks for testing this too guys!  I have a ton of updates coming + the live public website -- trying to get stuff done with my day job first
