### ISSUE TITLE
babel config

### ISSUE THREAD

**Issue by aretecode** [ladjs/lad#242]
[current .babelrc](https://github.com/crocodilejs/crocodile-node-mvc-framework/blob/development/.babelrc)

should update to use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) and [babel-preset-env](https://github.com/babel/babel-preset-env)

**Comment by Spence-S** [comment]
hey @aretecode does this satisfy? https://github.com/crocodilejs/babel-preset-crocodile/pull/1
