### ISSUE TITLE
bug: Missing default config values

### ISSUE THREAD

**Issue by OmgImAlexis** [ladjs/lad#257]
[`.env.defaults`](https://github.com/ladjs/lad/blob/master/template/.env.defaults) is missing `EMAIL_DEFAULT_FROM, GOOGLE_ANALYTICS, CURL_FILTER_TIMEOUT_MS`.

**Comment by niftylettuce** [comment]
Closed via https://github.com/ladjs/lad/commit/8022262f147b4642a0ecf152b8ebd2cf5d866239
