### ISSUE TITLE
bug: Incompatible library version

### ISSUE THREAD

**Issue by OmgImAlexis** [ladjs/lad#258]
@niftylettuce might be able to fix this with yarn's lock file.

```
[AGENDA] module.js:602
[AGENDA]   return process.dlopen(module, path._makeLong(filename));
[AGENDA]                  ^
[AGENDA] 
[AGENDA] Error: dlopen(/Users/xo/code/lad/template/node_modules/custom-fonts-in-emails/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
[AGENDA]   Referenced from: /Users/xo/code/lad/template/node_modules/custom-fonts-in-emails/node_modules/sharp/build/Release/sharp.node
[AGENDA]   Reason: Incompatible library version: sharp.node requires version 50.0.0 or later, but libvips-cpp.42.dylib provides version 48.0.0
[AGENDA]     at Object.Module._extensions..node (module.js:602:18)
[AGENDA]     at Module.load (module.js:507:32)
[AGENDA]     at tryModuleLoad (module.js:470:12)
[AGENDA]     at Function.Module._load (module.js:462:3)
[AGENDA]     at Module.require (module.js:517:17)
[AGENDA]     at require (internal/module.js:11:18)
[AGENDA]     at Object.<anonymous> (/Users/xo/code/lad/template/node_modules/custom-fonts-in-emails/node_modules/sharp/lib/constructor.js:9:15)
[AGENDA]     at Module._compile (module.js:573:30)
[AGENDA]     at Object.Module._extensions..js (module.js:584:
[AGENDA] 10)
[AGENDA]     at Module.load (module.js:507:32)
[AGENDA]     at tryModuleLoad (module.js:470:12)
[AGENDA]     at Function.Module._load (module.js:462:3)
[AGENDA]     at Module.require (module.js:517:17)
[AGENDA]     at require (internal/module.js:11:18)
[AGENDA]     at Object.<anonymous> (/Users/xo/code/lad/template/node_modules/custom-fonts-in-emails/node_modules/sharp/lib/index.js:3:15)
[AGENDA]     at Module._compile (module.js:573:30)
[AGENDA] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by lovell** [comment]
Is this after an upgrade from sharp v0.16.x to v0.18.x via yarn? My best guess would be that yarn is overwriting files in the existing `node_module\sharp` directory rather than replacing the whole directory. If so, this smells like a yarn bug/feature.

**Comment by OmgImAlexis** [comment]
That's from a new install of sharp. I even tried wiping my `node_modules` and the yarn cache.

**Comment by lovell** [comment]
@OmgImAlexis Thanks for checking. This is all rather odd as the
```
sharp.node requires version 50.0.0 or later, but libvips-cpp.42.dylib provides version 48.0.0
```
message suggests the pre-built libvips binaries provided for sharp v0.16.x are being used by sharp v0.18.x.

Is the latest version of yarn being used? I've had a quick look thought the list of open yarn issues to see if there's anything related to this but there are too many :(

There's discussion in https://github.com/lovell/sharp/issues/939 of adding verification to sharp to ensure the version of its pre-compiled libvips binaries are valid.

**Comment by pablopunk** [comment]
I had this issue and I fixed it with `brew install homebrew/science/vips --with-webp --with-graphicsmagick` and then `cd template/ && rm -rf node_modules && yarn install`

**Comment by niftylettuce** [comment]
We are removing Sharp completely from this project because it is unstable

**Comment by lovell** [comment]
Based on this issue, the forthcoming sharp v0.19.0 will add a verification step to ensure the version of the pre-compiled libvips binaries in the `node_modules/sharp/vendor` directory is as expected - see commit 7b6c803 for the details.
