### ISSUE TITLE
bug: 500 page not used by default

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#261]
I think this is an error with `koa-better-error-handler`, but for some reason it does not see our 500 error page in `template/views/500.pug`.  Simply trigger any internal server error to reproduce, and use `DEBUG=* node web.js` to test and see the debug output from `koa-better-error-handler`

**Comment by pablopunk** [comment]
I tried this and 500 errors do render our page (`template/app/views/500.pug`)

![screen shot 2017-09-11 at 3 23 33 pm](https://user-images.githubusercontent.com/4324982/30276472-4062258a-9705-11e7-9d57-c532c246997e.png)

**Comment by niftylettuce** [comment]
thx for testing
