### ISSUE TITLE
feature: use `ip` package to do `ip.address()` to get LAN network IP

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#262]
basically when `web.js` and `api.js` start up, we should use `ip` package and `ip.address()` to output to console the URL that it's running on (on the local area network)

**Comment by pablopunk** [comment]
I'll push this:
```go
[WEB] info: web server listening on 192.168.0.19:3000
[API] info: api server listening on 192.168.0.19:6000
```
