### ISSUE TITLE
feature: add swagger documentation for API with auto-generated API docs

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#265]
for example:

```js
/*
 * @api [get] /pets
 * description: "Returns all pets from the system that the user has access to"
 * responses:
 *   "200":
 *     description: "A list of pets."
 *     schema:
 *       type: "String"
 */

api.route('/pets', function() {
    /* Pet code 😺 */
});
```

so we comment out our API in and then run `swagger-inline` and then run `swagger-to-slate` and `swagger-codegen`.

References
* https://github.com/readmeio/swagger-inline
* https://github.com/lavkumarv/swagger-to-slate
* https://github.com/swagger-api/swagger-codegen

**Comment by OmgImAlexis** [comment]
Waiting on https://github.com/wcandillon/swagger-js-codegen/issues/190
