### ISSUE TITLE
bug: sweetalert2 - click off and it says "ERROR"

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#267]
right now if you run `yarn start` and then go to <http://localhost:3000/contact> and fill out the form it gives you a success message with sweetalert2.  however if you try to click off the modal/popup it brings up an error.  I believe this is because of what we're doing in `template/assets/js/flash.js` with queueing.

reference:
https://limonte.github.io/sweetalert2/

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
