### ISSUE TITLE
docs: add documentation for how to setup SSL

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#276]
setting up SSL is fairly simple, but we need to document it.  there might also need to be a patch made to `template/config.index.js` to make adding SSL even simpler

https://github.com/ladjs/lad/blob/master/template/config/index.js#L65-L68

basically to get SSL to work we have to modify that config block above to be something like:

```js
ssl: {
  web: {
    key: fs.readFileSync(env.SSL_WEB_KEY, 'utf8'),
    cert: fs.readFileSync(env.SSL_WEB_CERT, 'utf8'),
    ca: fs.readFileSync(env.SSL_WEB_CA, 'utf8')
  },
  // ...
}
```

and then in `.env.defaults` and `.env.schema` we have to add:

```env
SSL_WEB_KEY=
SSL_WEB_CERT=
SSL_WEB_CA=
...
```

same thing for the API!

of course these env var names could be changed to some other better naming convention.

by default if the protocol `https` is detected it will utilize the SSL config object, e.g.
 <https://github.com/ladjs/lad/blob/master/template/web.js#L200>

here's a checklist:
- [ ] Add config object (e.g. `env.SSL_WEB_KEY ? fs.readFileSync(env.SSL_WEB_KEY, 'utf8') || ''` to the config block above - it should work even if SSL is not enabled) - this needs done for both web and api
- [ ] Ensure you've added documentation as to how to set up SSL (e.g. specify the user needs to ensure their protocol in `.env` file is set to `https`, port is set to `443`, and the paths are specified)
- [ ] Write a test using LetsEncrypt or some self-signed cert

**Comment by OmgImAlexis** [comment]
@niftylettuce it may also be worth it to check if the `env` fields are paths or strings as this would allow people using DOKKU, etc. to just pass the key in the env instead of needing to map the key to a file.
