### ISSUE TITLE
bug: the default/first user created should get assigned to admin group

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#278]
not sure where the best place to do this is, but we should make the first user created/signed up get admin privilege

probably in the users find or create functionality, do a count or something, if it's 0 then give user admin group.

user's are signed up here <https://github.com/ladjs/lad/blob/master/template/app/controllers/web/auth.js#L93-L96> so probably right before that code block something like:

```js
  // register the user
  try {
    const count = await Users.count({ group: 'admin' });
    const user = await Users.registerAsync(
      { email: ctx.req.body.email, group: count === 0 ? 'admin' : ' user' },
      ctx.req.body.password
    );
```

**Comment by niftylettuce** [comment]
related to #277

**Comment by pablopunk** [comment]
That worked, I'll push the fix right now
