### ISSUE TITLE
feature: add `opn` to open browser in gulp script upon start

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#281]
one time only when a user `yarn start`'s it should use the [opn][] package to run `await opn(config.urls.web, { wait: false });` in `template/gulpfile.js` so that it opens the user's browser for them!

[opn]: https://github.com/sindresorhus/opn

**Comment by niftylettuce** [comment]
also, this should only occur for development environment `config.env === 'development'`

**Comment by OmgImAlexis** [comment]
`opn` shouldn't run if nodemon hits an error.

I think we can use the nodemon api to check before running `opn` for the first time.

**Comment by pablopunk** [comment]
Got it. I was out for the weekend I'll check it when I get home.

**Comment by pablopunk** [comment]
Should we use [gulp-nodemon](https://www.npmjs.com/package/gulp-nodemon) to check for errors?
