### ISSUE TITLE
discussion: add out of the box SSL with our own subdomain

### ISSUE THREAD

**Issue by OmgImAlexis** [ladjs/lad#287]
Since let's encrypt certs are only valid for 90 days we can issue a cert for a subdomains we own.
To make sure users can't access cookies on our main site we'll need to use another domain like `ladjs-hosts.com` with their domain residing on `random_id.ladjs-hosts.com`.

We also need to add that domain to the [`public suffix list`](https://publicsuffix.org/) so Google, etc. all know each subdomain is different site.

**Comment by pablopunk** [comment]
I would like that feature, just like ▲ZEIT does with [now.sh](https://now.sh)
