### ISSUE TITLE
tests: write a basic test for API and web to hit all public endpoints to get 200 code w/supertest/superagent or something

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#305]

**Comment by OmgImAlexis** [comment]
Started with https://github.com/ladjs/lad/commit/e9c4167bdd125c5c1c9ca66e90ca1e01b874e2d6 and https://github.com/ladjs/lad/commit/39d0d4f9d0d98a47d742f0220007ffc5bba790b7
