### ISSUE TITLE
feature: convert jobs/email and jobs/locales into @ladjs/email and @ladjs/locales

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#309]

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/ladjs/email

@niftylettuce do we have a list of email transports we want to support? I know right now we use nodemailer but others may want to use an API based service like mailgun. We could either add seperate files for each or ship with a few packages like [nodemailer-mailgun-transport](https://www.npmjs.com/package/nodemailer-mailgun-transport).

**Comment by OmgImAlexis** [comment]
Should we move `getPaths` to a new lad package?

```
// TODO: this should be a package or we should use one that does same thing
// taken from:
// <https://github.com/queckezz/koa-views/blob/master/src/index.js>
```

**Comment by niftylettuce** [comment]
Yeah @OmgImAlexis that works here - and then perhaps you could fork koa-views and make our own using this?
