### ISSUE TITLE
Can't create Project ` command not found: lad`

### ISSUE THREAD

**Issue by eikebartels** [ladjs/lad#335]
`~/D/P/lad » npm install -g lad
+ lad@0.0.1
updated 1 package in 0.492s
~/D/P/lad » lad new-project
zsh: correct 'lad' to 'ld' [nyae]? n
zsh: command not found: lad`

Any idea?

**Comment by eikebartels** [comment]
Ok it works if I download directly from git 
`npm install -g https://github.com/ladjs/lad.git`

**Comment by batjko** [comment]
I still run into this issue on Ubuntu 18.04, with Node 10, using yarn.

I feel like this should probably not have been closed, given that the instructions in the lad docs are not to download directly from git, and the normal installation via package managers should be working.

**Comment by OmgImAlexis** [comment]
@niftylettuce shall we reopen until v1?

**Comment by batjko** [comment]
@OmgImAlexis The last commit on this repo was 5 months ago. Is the project still being maintained / developed?

**Comment by OmgImAlexis** [comment]
Yes if you look at the code you'll notice we split a lot of the code up to other submodules and they're all being worked on.

**Comment by batjko** [comment]
Ah.
I just noticed that whatever is still in npm is a 1yr old and deprecated:
https://www.npmjs.com/package/lad ...explaining the issue, of course.

But the readme still instructs to install the npm version. Perhpas, while development is still going on, just updating the README would be enough?

**Comment by niftylettuce** [comment]
Lad beta is released. v0.2.3 is available

```sh
npm install -g lad@latest
```

```sh
lad --help
```

```sh
lad <my project name>
```

**Comment by niftylettuce** [comment]
Today I'm happy to announce the launch of v1.0.0 LTS codenamed “Jack” of Lad; the best Node.js framework in existence. This project started publicly on 9/4/17 and I’m thrilled to release it today on 12/11/19. Try out the demo @ https://lad.sh + source @ https://github.com/ladjs/lad.
