### ISSUE TITLE
Commnand not found using node 9.4.0 on macos

### ISSUE THREAD

**Issue by paivaric** [ladjs/lad#338]
$ yarn global add lad
yarn global v1.3.2
[1/4] 🔍  Resolving packages...
warning lad@0.0.1: Please email niftylettuce@gmail.com if you'd like to get notified when a stable version of Lad is released.  Thank you
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
**warning "lad@0.0.1" has no binaries**
✨  Done in 0.49s.

$ lad
-bash: lad: command not found

**Comment by pablopunk** [comment]
@paivaric please see https://github.com/ladjs/lad/issues/335

**Comment by paivaric** [comment]
tks


*Ricardo Paiva*
(12) 98238-3611
linkedin.com/in/ricardopaiva


2018-02-18 12:25 GMT-03:00 Pablo Varela <notifications@github.com>:

**Comment by niftylettuce** [comment]
Today I'm happy to announce the launch of v1.0.0 LTS codenamed “Jack” of Lad; the best Node.js framework in existence. This project started publicly on 9/4/17 and I’m thrilled to release it today on 12/11/19. Try out the demo @ https://lad.sh + source @ https://github.com/ladjs/lad.
