### ISSUE TITLE
Port: Agenda to Bull

### ISSUE THREAD

**Issue by builtbyproxy** [ladjs/lad#344]
From what I can see, whilst important, [Agenda][agendaLink] isnt to heavily embedded into the core functionality to prevent us from switching to [Bull][bullLink] whilst we have the chance. 

This issue is to document and discuss the process of changing this. For quick reference this is a popular breakdown of what each does;

| Feature         | Bull          | Kue   | Bee | Agenda |
| :-------------  |:-------------:|:-----:|:---:|:------:|
| Backend         | redis         | redis |redis| mongo  |
| Priorities      | ✓             |  ✓    |     |   ✓    |
| Concurrency     | ✓             |  ✓    |  ✓  |   ✓    |
| Delayed jobs    | ✓             |  ✓    |     |   ✓    |
| Global events   | ✓             |  ✓    |     |        |
| Rate Limiter    | ✓             |       |     |        |
| Pause/Resume    | ✓             |  ✓    |     |        |
| Sandboxed worker| ✓             |       |     |        |
| Repeatable jobs | ✓             |       |     |   ✓    |
| Atomic ops      | ✓             |       |  ✓  |        |
| Persistence     | ✓             |   ✓   |  ✓  |   ✓    |
| UI              | ✓             |   ✓   |     |   ✓    |
| Optimized for   | Jobs / Messages | Jobs | Messages | Jobs |

 [bullLink]: <https://github.com/OptimalBits/bull/>
 [agendaLink]: <https://github.com/agenda/agenda>

**Comment by builtbyproxy** [comment]
Jobs are now stored in Redis with the use of Bull
![Redis Store](https://i.gyazo.com/e7f0a685e034da8bcbf30dc991f0661c.png)

WIP: 
- [ ] Schedule Jobs
- [ ] Preview Email
- [ ] Cleanup

**Comment by shaunwarman** [comment]
Here's an initial stab at a lad bull client
https://github.com/shaunwarman/bull

Will work on lad agenda -> bull to see what issues pop up.
