### ISSUE TITLE
'lad' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by moe70** [ladjs/lad#361]
I'm trying to get started with lad.js and I am following this [tutorial](https://lad.js.org/#/?id=install). I am on windows using webstorm. I ran `npm install -g lad` which gave the following message

> npm WARN deprecated lad@0.0.1: Please email niftylettuce@gmail.com if you'd like to get notified when a stable version of Lad is released.  Thank you
> + lad@0.0.1
> updated 1 package in 1.228s

But when I run `lad new-project` i only get 

> 'lad' is not recognized as an internal or external command,

Is the tutorial missing some steps?

**Comment by niftylettuce** [comment]
Lad beta is released. v0.2.3 is available

```sh
npm install -g lad@latest
```

```sh
lad --help
```

```sh
lad <my project name>
```

**Comment by niftylettuce** [comment]
Today I'm happy to announce the launch of v1.0.0 LTS codenamed “Jack” of Lad; the best Node.js framework in existence. This project started publicly on 9/4/17 and I’m thrilled to release it today on 12/11/19. Try out the demo @ https://lad.sh + source @ https://github.com/ladjs/lad.
