### ISSUE TITLE
GET params get duplicated if no locale is provided

### ISSUE THREAD

**Issue by phumberdroz** [ladjs/lad#372]
Hey,

not sure if this is an `ladjs/i18n` issue I just took a brief look at the redirect implementation.
But if you goto: [https://lad.sh?test=test?test=test?test=test%3Ftest%3Dtest](https://lad.sh?test=test?test=test?test=test%3Ftest%3Dtest)
you can see it.

**Comment by niftylettuce** [comment]
Awesome find, will fix along with other one

**Comment by niftylettuce** [comment]
We have resolved this as of v3.0.0 released to npm :tada:

There are two new options added `redirectIgnoresNonGetMethods` (Boolean, defaults to `true`) and `stringify` (Object for [qs.stringify](https://github.com/ljharb/qs), and has sensible industry standard defaults of `{ addQueryPrefix: true, format: 'RFC1738', arrayFormat: 'indices' }`).  As of v3.0.0 all non-GET requests will *NOT* be redirected to locale specific path.  If you wish to turn this behavior off, pass `new I18n({ redirectIgnoresNonGetMethods: false })`.

```sh
npm install @ladjs/i18n@latest
```

or with yarn:

```sh
yarn add @ladjs/i18n@latest
```

Note that we have also version bumped deps in `@ladjs/web` and `@ladjs/api` (as well as across all of @ladjs and @cabinjs projects), and you can install the latest with `@ladjs/web@latest` and `@ladjs/api@latest`.

Let me know if you find any further issues, thanks so much!
