### ISSUE TITLE
Question - Deployment and using the proxy

### ISSUE THREAD

**Issue by Rotho98** [ladjs/lad#375]
I am having some issues utilizing the proxy correctly, I can run all the microservices without issue but I have no clue on how to use the proxy correctly! Do I direct traffic to it and it will figure out *_HOSt from the .env what service to run? Or do I have to do something else? I currently am using an apache reverse proxy, I have set up an Nginx one as well as fully understand DNS, so if I have to utilize them someway let me know, please!

Apart from that I am loving lad and plan to use it for all my client and personal projects

**Comment by niftylettuce** [comment]
Here's a guide for you that I use (it shows how you port forward 80 -> 8080 and 443 -> 8443 using iptables via ufw).

I am eventually going to turn this into a blog post:

https://gist.github.com/niftylettuce/57eff009d5575e22855b6f67c046fd7d

**Comment by niftylettuce** [comment]
All the proxy does is redirect traffic from http to https.  I recommend running it on any server that you have the API or Web servers running, and use the setup I have (see previous comment) to do port forwarding with ufw.
