### ISSUE TITLE
npm ERR! 404 Not Found - GET https://codeload.github.com/niftylettuce/svgfont2js/tar.gz/376ca0b5498ea4fa08b1955ecd5bb11c1014a401 

### ISSUE THREAD

**Issue by nitetrik** [ladjs/lad#421]
I have got this error when creating a new project with lad,

npm ERR! code E404
npm ERR! 404 Not Found - GET https://codeload.github.com/niftylettuce/svgfont2js/tar.gz/376ca0b5498ea4fa08b1955ecd5bb11c1014a401
npm ERR! 404 
npm ERR! 404  'svgfont2js@https://codeload.github.com/niftylettuce/svgfont2js/tar.gz/376ca0b5498ea4fa08b1955ecd5bb11c1014a401' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Thanks, Nitetrik

**Comment by titanism** [comment]
please try v1.3.2 of lad or reference the codebase at https://github.com/forwardemail/forwardemail.net
